In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [1]:
import numpy as np


In [3]:
set1={"aman","222",777,400.4}
x=tuple(set1)
print (x)

(400.4, 'aman', 777, '222')


In [4]:
dict={"roll_no":20235,"name":"mahasri","last_name:":"V","date_of_birth":"21.01.2003"}
print(dict)

{'roll_no': 20235, 'name': 'mahasri', 'last_name:': 'V', 'date_of_birth': '21.01.2003'}


In [5]:
import random as rand


In [17]:
np.random.randint(4,size=(4,5))
#np.random is a module---rand is a function in that

array([[1, 0, 0, 1, 1],
       [1, 0, 0, 0, 2],
       [0, 3, 2, 3, 0],
       [1, 2, 1, 2, 0]])

In [18]:
np.random.rand(1)



array([0.44861109])

In [19]:
x=-1234
np.absolute(x)

1234

In [22]:
np.random.randint(20,90)

21

In [40]:
set1={11,12,13,14,15}
a=[]
for i in range(len(set1)):
  a.append(i)
print(a)
print(set1)
np.random.choice(set1)

[0, 1, 2, 3, 4]
{11, 12, 13, 14, 15}


ValueError: ignored

In [45]:
file1=open("myfile.txt","w")

In [46]:
file1.write("The King is Dead, Long Live The King")
file1.close()

In [47]:
file1=open("myfile.txt","r")
print(file1.read())

The King is Dead, Long Live The King


In [48]:
file1.close()


In [56]:
def functions(a,b,c):
  if a>b:
    if a>c:
      print(a)
  elif b>c:
      print (b)

  else:
      print(c)
functions(10,20,30)
  

30


In [58]:
def loops():
  i=0
  while(i<5):
    print(i)
    if(i==1):
      continue
    else:
      break
loops()


0


In [63]:
string="    The King is Dead, Long Live The King      "
print(string)
print(string[0])
print(string[3:6])
print(string[3:])
print(string.split())
print(string.strip())

    The King is Dead, Long Live The King      
 
 Th
 The King is Dead, Long Live The King      
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']
The King is Dead, Long Live The King


In [64]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [70]:
list1=[1,2,4,5,8]
x=np.array(list1)
print(x[:2])


[1 2]


In [77]:
x=np.array([[1,2,3],[4,5,6]])
print(x[1:])

[[4 5 6]]


In [86]:
x=np.array([[1,2,3],[4,5,6]])
y=x.reshape(-1)
print(y)
print(y.shape)

[1 2 3 4 5 6]
(6,)


In [87]:
array=[1,2,3]
sum=0
for i in range(len(array)):
  sum=sum+array[i]
print(sum)

6


In [90]:

array=[77,74,75]
pro=1
for i in range(len(array)):
  pro=pro*array[i]
print(pro)

427350


In [95]:
arr1=[1,2,3]
arr2=[4,5,6]
pro=0
for i in range(len(arr1)):
  for j in range(len(arr2)):
    if i==j:
      pro=pro+arr1[i]*arr2[j]
print(pro)
  
    

32


In [99]:
arr=[1,1,4,5,5,5,7]
arr1=[]
for i in range(len(arr)):
  if arr[i] not in arr1:
    arr1.append(arr[i])
print(arr1)

[1, 4, 5, 7]


In [100]:
list1=[1,2,3]
arr=np.array(list1)
print(arr)

[1 2 3]


In [101]:
arr=np.array([1,2,3])
arr.fill(9)
print(arr)

[9 9 9]


In [104]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [115]:
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.median(arr))
print(np.argmax(arr))
print(np.argmin(arr))



12.461538461538462
19.165736192147232
367.32544378698225
56
1
2.0
12
1


In [119]:
arr=np.array([[2,-12],[1,-5]])
x,y=np.linalg.eig(arr)
print(x)
print(y)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [123]:
arr=np.array([[11, 22, 11, 31],[25, 33, 31, 28]])
result = np.corrcoef(arr)

print(result)


[[1.         0.15997968]
 [0.15997968 1.        ]]
